# Generated by Django 4.0.4 on 2022-05-17 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('idBicicleta', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Patente')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca')),
                ('descripcionTipoBicicleta', models.CharField(max_length=50, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='tipoBicicleta',
            fields=[
                ('idTipoBicicleta', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id tipo bicicleta')),
                ('nombreTipoBicicleta', models.CharField(max_length=20, verbose_name='Nombre tipo de bicicleta')),
            ],
        ),
        migrations.RemoveField(
            model_name='tiposervicio',
            name='servicio',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
        migrations.DeleteModel(
            name='tipoServicio',
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='tipoBicicleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.tipobicicleta'),
        ),
    ]
