# Generated by Django 4.0.4 on 2022-05-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_bicicleta_tipobicicleta_remove_tiposervicio_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicicleta',
            name='precio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='descripcionTipoBicicleta',
            field=models.CharField(max_length=300, verbose_name='Descripción'),
        ),
    ]
