# Generated by Django 4.0.4 on 2022-05-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0003_bicicleta_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='precio',
            field=models.IntegerField(default=0, verbose_name='Marca'),
        ),
    ]
