# Generated by Django 4.0.4 on 2022-05-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0004_alter_bicicleta_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bicicleta',
            old_name='descripcionTipoBicicleta',
            new_name='descripcionBicicleta',
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='idBicicleta',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='id bicicleta'),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='precio',
            field=models.IntegerField(default=0, verbose_name='Precio'),
        ),
    ]
