# Generated by Django 3.1.2 on 2022-05-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0006_auto_20220529_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
